### ISSUE TITLE
MonthUpDownPageProvider pageLimit.upLimit returns 0, when bring app to a foreground (IOS)

### ISSUE THREAD

**Issue by BigMenya** [Macacoazul01/month_picker_dialog#106]
From my perspective its in month_selector.dart (method initialize()) only gets call on initState), when just a build method gets called, bringing to foreground is leading to it. Up limit of MonthUpDownPageProvider doesn't update which lead to a zero.

![Screenshot 2024-09-03 at 15 24 37](https://github.com/user-attachments/assets/8ef7cc59-93be-4088-ba8f-9d2f25aded59)

**Comment by Macacoazul01** [comment]
Can you send any sample code that generates this error?

**Comment by BigMenya** [comment]
Unfortunately I don't. I have tried to create an example but it doesn't reproduces since build is not triggered.
At least I know that is a part of a project environment.
But anyway there is to many options why builder can be triggered. 

 it's triggered by builder function here when app goes to background
   final DateTime? dialogDate = await showDialog<DateTime>(
    context: context,
    barrierDismissible: dismissible,
    builder: (BuildContext context) {
      return MultiProvider(
        providers: [
          ChangeNotifierProvider.value(
            value: YearUpDownPageProvider(),
          ),
          ChangeNotifierProvider.value(
            value: MonthUpDownPageProvider(),
          ),
        ],
        child: MonthPickerDialog(controller: controller),
      );
    },
  );

**Comment by Macacoazul01** [comment]
Tested here with the new 5.1.3 and everything seems to be ok.
Please reopen if not
