### ISSUE TITLE
Need Update

### ISSUE THREAD

**Issue by ECeternalcat** [Macacoazul01/month_picker_dialog#107]
When i creative a new project,I get this: Because month_picker_dialog 5.1.3 depends on intl ^0.19.0 and no versions of month_picker_dialog match >5.1.3 <6.0.0, month_picker_dialog ^5.1.3 requires intl ^0.19.0.
The intl Ver is 0.20.1

**Comment by Macacoazul01** [comment]
fixed in 5.2.0
