### ISSUE TITLE
Transfering ownership of this repo

### ISSUE THREAD

**Issue by hmkrivoj** [Macacoazul01/month_picker_dialog#82]
Hello, I'd like to transfer ownership of this repo. 

@Macacoazul01 Would you like to have it transfered to your profile or should I transfer it to a new organization?

**Comment by Macacoazul01** [comment]
You can send to my profile

**Comment by hmkrivoj** [comment]
Thank you, happy to do so but I need you to delete your fork first

![grafik](https://github.com/hmkrivoj/month_picker_dialog/assets/32704196/1467488b-6bb8-4bcf-b628-3cc92f3252be)

**Comment by Macacoazul01** [comment]
done
