### ISSUE TITLE
the calendar widget in tablet is different from the landscape and portrait,  is there any way to reduce the width?

### ISSUE THREAD

**Issue by UnnimayaR** [Macacoazul01/month_picker_dialog#84]
the calendar widget in tablet is different from the landscape and portrait, 

![Capture](https://github.com/Macacoazul01/month_picker_dialog/assets/130346311/d2d83063-6f6d-4cf8-93bc-8a58c982743d)

**Comment by Macacoazul01** [comment]
What's your flutter and package versions?

**Comment by Macacoazul01** [comment]
try using 2.5.1
If it isnt fixed there, please reopen the issue
