### ISSUE TITLE
A RenderFlex overflowed

### ISSUE THREAD

**Issue by ThatPham2000** [Macacoazul01/month_picker_dialog#85]
**Video:**

https://github.com/Macacoazul01/month_picker_dialog/assets/57900109/6a43649a-ad7b-49ec-a048-add89f2c9524

**My flutter doctor:**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on macOS 13.6.1 22G313 darwin-arm64, locale
    en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.4)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

**Comment by Macacoazul01** [comment]
It happens because the widget is bigger than where you are trying to show it

**Comment by Macacoazul01** [comment]
You can try to create a PR to make the widget responsive

You can try to create a PR to add a parameter "forcePortrait" to add the option to block the widget from being presented in landscape mode.

OR 

There are some options as this is being presented in landscape mode (not sure if any will work):

You can change your orientation to portrait when the size of the screen is less than a determined value.

You can change the widget size based on the screen (or on creation).

You can try to wrap it around something scrollable.

**Comment by Macacoazul01** [comment]
> You can try to create a PR to add a parameter "forcePortrait" to add the option to block the widget from being presented in landscape mode.

Added in 2.5.0

**Comment by ThatPham2000** [comment]
A RenderFlex still overflowed although I used "forcePortrait". I think it will be better when adding scrollable instead of this bug.

**Comment by Macacoazul01** [comment]
I told you it would happen

**Comment by Macacoazul01** [comment]
@ThatPham2000 have you tried anything to fix this error?

**Comment by Macacoazul01** [comment]
Tried some options but none worked...

Wraping the content inside a Scrollview breaks the borders and causes a scroll that overlaps with the list.
Would have to create an option to block the list from scrolling also...

If you find something that works, please let me know.

**Comment by Macacoazul01** [comment]
Probably fixed in 2.10.0
