### ISSUE TITLE
Version solving failed for intl: 0.19.0

### ISSUE THREAD

**Issue by dwzrlp** [Macacoazul01/month_picker_dialog#90]
Because month_picker_dialog 2.11.0 depends on intl ^0.18.1 and no versions of month_picker_dialog match >2.11.0 <3.0.0, month_picker_dialog ^2.11.0 requires intl ^0.18.1.
So, because smart_by_jarod depends on both intl ^0.19.0 and month_picker_dialog ^2.11.0, version solving failed.

**Comment by Macacoazul01** [comment]
I was waiting for someone to request this as not everyone is using flutter 3.19 and some other updates to the package landed that didnt need this flutter version.

Probably im gonna wait a little more to bump intl version, but you can use a dependency override to fix this until this update is released:
#57

**Comment by dwzrlp** [comment]
> I was waiting for someone to request this as not everyone is using flutter 3.19 and some other updates to the package landed that didnt need this flutter version.
> 
> Probably im gonna wait a little more to bump intl version, but you can use a dependency override to fix this until this update is released: #57

Thanks

**Comment by Macacoazul01** [comment]
This will launch on 3.0

**Comment by Macacoazul01** [comment]
![image](https://github.com/Macacoazul01/month_picker_dialog/assets/57464965/bd5208e0-945c-4e98-b64a-2793b7889623)
Cant bump intl to 0.19 yet.

**Comment by esaiamuthan** [comment]
Yes the same issue occurs for me also

Can anyone make this fix and let us know. it will be helpful for us to solve it

**Comment by Macacoazul01** [comment]
Avaliable in 3.0
