### ISSUE TITLE
[Feature] - range selection

### ISSUE THREAD

**Issue by Macacoazul01** [Macacoazul01/month_picker_dialog#94]
Is this a need for anyone using the package?

**Comment by lautarozanuttini** [comment]
Hello im using this package and it would be a usefull upgrade

**Comment by Macacoazul01** [comment]
You are thinking in a selection that returns all the months between the two selected or just the borders?

**Comment by lautarozanuttini** [comment]
Hi, it would be very usefull select between two month to bring data in that period for example from 1 Jan to 31 Mar when you select January and March.

**Comment by lautarozanuttini** [comment]
If you need a colaborator to this task, tell me and i will work in a pull request with this change.

**Comment by Macacoazul01** [comment]
If you can, please send the pr. 
I will look it later tonight

**Comment by lautarozanuttini** [comment]
sorry i cant do it today, let me see in this days and i will clone the repository to do the pr.

**Comment by Macacoazul01** [comment]
@lautarozanuttini please use the new parameter `rangeMode` from the controller

**Comment by lautarozanuttini** [comment]
Hello @Macacoazul01 i have finish with this new feature and add the pull request! thanks

**Comment by Macacoazul01** [comment]
@lautarozanuttini reviewed and fixed some bugs.
Its avaliable in version `4.0.0`

**Comment by Macacoazul01** [comment]
Tks for the PR!

**Comment by lautarozanuttini** [comment]
Thank you to trust and let me collaborate
